# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: sporkus_le_capybara
  - board: sporkus_le_capybara
    snippet: enable_ec_calibrator
    artifact-name: sporkus_le_capybara_calibrator
  - board: lpgalaxy_le_zapybara
  - board: lpgalaxy_le_zapybara
    snippet: enable_ec_calibrator
    artifact-name: lpgalaxy_le_zapybara_calibrator
